# Name Project
spring.application.name=Proyecto capas

# Configuracion Basica

# direccion la BD
spring.datasource.url=jdbc:postgresql://localhost:5432/gestion_libros
# nombre usuario en postgres
spring.datasource.username=postgres
# contraseña en postgres
spring.datasource.password=As@5010.com
# traductor de spring para comunicarse con postgres
spring.datasource.driver-class-name=org.postgresql.Driver

# Configuracion JPA/Hibernate

# gestion esquema con -update-> actualizamos datos automaticamente
spring.jpa.hibernate.ddl-auto=update
# muestra codigo sql en consola despues de caa consulta
spring.jpa.show-sql=true
# indica a hibernate usar el lenguaje de postgresql
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
# hace que el lenguaje sql que sale en consola sea legible y ordenado
spring.jpa.properties.hibernate.format_sql=true

